### ISSUE TITLE
expose function that parses `comment(collection_id)` relation naming convention

### ISSUE THREAD

**Issue by rentzsch** [rentzsch/jsongo#3]

**Comment by alex996** [comment]
I suppose this is already done in [`6610d62` commit](https://github.com/rentzsch/jsongo/commit/6610d623a3c31f00c0faf6f69f99f501061b8a53#diff-79bc6bc1aaf754b4b6c765385b370912R197)? The func will likely move to a base `Model` class eventually.

**Comment by rentzsch** [comment]
Yup, it sure looks like it.
